/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StoreOrdersRouteImport } from './routes/_store/orders'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as DeskQueueRouteImport } from './routes/desk/$queue'
import { Route as StoreRequestsIndexRouteImport } from './routes/_store/requests.index'
import { Route as StoreRequestsRequestIdRouteImport } from './routes/_store/requests.$requestId'
import { Route as DeskQueueIndexRouteImport } from './routes/desk/$queue.index'
import { Route as DeskQueueRequestIdRouteImport } from './routes/desk/$queue.$requestId'
import { Route as StoreOrdersOrderIdRefundRouteImport } from './routes/_store/orders.$orderId.refund'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskQueueRoute = DeskQueueRouteImport.update({
  id: '/$queue',
  path: '/$queue',
  getParentRoute: () => DeskRoute,
} as any)
const StoreRequestsIndexRoute = StoreRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRequestsRequestIdRoute = StoreRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => StoreRoute,
} as any)
const DeskQueueIndexRoute = DeskQueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskQueueRoute,
} as any)
const DeskQueueRequestIdRoute = DeskQueueRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => DeskQueueRoute,
} as any)
const StoreOrdersOrderIdRefundRoute =
  StoreOrdersOrderIdRefundRouteImport.update({
    id: '/$orderId/refund',
    path: '/$orderId/refund',
    getParentRoute: () => StoreOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/policy': typeof PolicyRoute
  '/sign-in': typeof SignInRoute
  '/orders': typeof StoreOrdersRouteWithChildren
  '/desk/$queue': typeof DeskQueueRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/requests/$requestId': typeof StoreRequestsRequestIdRoute
  '/desk/$queue/$requestId': typeof DeskQueueRequestIdRoute
  '/requests/': typeof StoreRequestsIndexRoute
  '/desk/$queue/': typeof DeskQueueIndexRoute
  '/orders/$orderId/refund': typeof StoreOrdersOrderIdRefundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policy': typeof PolicyRoute
  '/sign-in': typeof SignInRoute
  '/orders': typeof StoreOrdersRouteWithChildren
  '/desk': typeof DeskIndexRoute
  '/requests/$requestId': typeof StoreRequestsRequestIdRoute
  '/desk/$queue/$requestId': typeof DeskQueueRequestIdRoute
  '/requests': typeof StoreRequestsIndexRoute
  '/desk/$queue': typeof DeskQueueIndexRoute
  '/orders/$orderId/refund': typeof StoreOrdersOrderIdRefundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_store': typeof StoreRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/policy': typeof PolicyRoute
  '/sign-in': typeof SignInRoute
  '/_store/orders': typeof StoreOrdersRouteWithChildren
  '/desk/$queue': typeof DeskQueueRouteWithChildren
  '/desk/': typeof DeskIndexRoute
  '/_store/requests/$requestId': typeof StoreRequestsRequestIdRoute
  '/desk/$queue/$requestId': typeof DeskQueueRequestIdRoute
  '/_store/requests/': typeof StoreRequestsIndexRoute
  '/desk/$queue/': typeof DeskQueueIndexRoute
  '/_store/orders/$orderId/refund': typeof StoreOrdersOrderIdRefundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/policy'
    | '/sign-in'
    | '/orders'
    | '/desk/$queue'
    | '/desk/'
    | '/requests/$requestId'
    | '/desk/$queue/$requestId'
    | '/requests/'
    | '/desk/$queue/'
    | '/orders/$orderId/refund'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policy'
    | '/sign-in'
    | '/orders'
    | '/desk'
    | '/requests/$requestId'
    | '/desk/$queue/$requestId'
    | '/requests'
    | '/desk/$queue'
    | '/orders/$orderId/refund'
  id:
    | '__root__'
    | '/'
    | '/_store'
    | '/desk'
    | '/policy'
    | '/sign-in'
    | '/_store/orders'
    | '/desk/$queue'
    | '/desk/'
    | '/_store/requests/$requestId'
    | '/desk/$queue/$requestId'
    | '/_store/requests/'
    | '/desk/$queue/'
    | '/_store/orders/$orderId/refund'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRouteWithChildren
  DeskRoute: typeof DeskRouteWithChildren
  PolicyRoute: typeof PolicyRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/orders': {
      id: '/_store/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$queue': {
      id: '/desk/$queue'
      path: '/$queue'
      fullPath: '/desk/$queue'
      preLoaderRoute: typeof DeskQueueRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_store/requests/': {
      id: '/_store/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof StoreRequestsIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/requests/$requestId': {
      id: '/_store/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof StoreRequestsRequestIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/desk/$queue/': {
      id: '/desk/$queue/'
      path: '/'
      fullPath: '/desk/$queue/'
      preLoaderRoute: typeof DeskQueueIndexRouteImport
      parentRoute: typeof DeskQueueRoute
    }
    '/desk/$queue/$requestId': {
      id: '/desk/$queue/$requestId'
      path: '/$requestId'
      fullPath: '/desk/$queue/$requestId'
      preLoaderRoute: typeof DeskQueueRequestIdRouteImport
      parentRoute: typeof DeskQueueRoute
    }
    '/_store/orders/$orderId/refund': {
      id: '/_store/orders/$orderId/refund'
      path: '/$orderId/refund'
      fullPath: '/orders/$orderId/refund'
      preLoaderRoute: typeof StoreOrdersOrderIdRefundRouteImport
      parentRoute: typeof StoreOrdersRoute
    }
  }
}

interface StoreOrdersRouteChildren {
  StoreOrdersOrderIdRefundRoute: typeof StoreOrdersOrderIdRefundRoute
}

const StoreOrdersRouteChildren: StoreOrdersRouteChildren = {
  StoreOrdersOrderIdRefundRoute: StoreOrdersOrderIdRefundRoute,
}

const StoreOrdersRouteWithChildren = StoreOrdersRoute._addFileChildren(
  StoreOrdersRouteChildren,
)

interface StoreRouteChildren {
  StoreOrdersRoute: typeof StoreOrdersRouteWithChildren
  StoreRequestsRequestIdRoute: typeof StoreRequestsRequestIdRoute
  StoreRequestsIndexRoute: typeof StoreRequestsIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreOrdersRoute: StoreOrdersRouteWithChildren,
  StoreRequestsRequestIdRoute: StoreRequestsRequestIdRoute,
  StoreRequestsIndexRoute: StoreRequestsIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface DeskQueueRouteChildren {
  DeskQueueRequestIdRoute: typeof DeskQueueRequestIdRoute
  DeskQueueIndexRoute: typeof DeskQueueIndexRoute
}

const DeskQueueRouteChildren: DeskQueueRouteChildren = {
  DeskQueueRequestIdRoute: DeskQueueRequestIdRoute,
  DeskQueueIndexRoute: DeskQueueIndexRoute,
}

const DeskQueueRouteWithChildren = DeskQueueRoute._addFileChildren(
  DeskQueueRouteChildren,
)

interface DeskRouteChildren {
  DeskQueueRoute: typeof DeskQueueRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskQueueRoute: DeskQueueRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRouteWithChildren,
  DeskRoute: DeskRouteWithChildren,
  PolicyRoute: PolicyRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
